### PR TITLE
Added code of conduct message

### PR DESCRIPTION
**Pull request by AverageMarcus**

### CODE REVIEW

**Comment by spikeheap** [comment]
It'd be good to use a CoC URL from JSOxford/DO rather than a personal repo. I like the intention of this, though I wonder if Slack provides a sticky header message instead which would solve the same problem.

**Comment by AverageMarcus** [comment]
Pretty sure @peterjwest looked into a sticky header sort of solution but I don't think Slack has the ability.

**Comment by thisjunewest** [comment]
We can make a post sticky, but it only shows up in the details pane.

Does this send a DM to that user, or does it post a message in #general?

**Comment by AverageMarcus** [comment]
This will post straight in #general. I can look into sending a DM. 

I thought having it in general might be good as it will also be seen by original JSOx members that joined before the migration.

**Comment by AverageMarcus** [comment]
_(Leaving this here for me to test out later)_

For DM:

```
robot.send({room: msg.message.user.name}, "Hi @" + msg.message.user.name + "! :wave: Please make sure you have read our Code of Conduct here: http://peterjwest.github.io/do-coc/");
```

**Comment by AverageMarcus** [comment]
I've updated it to send the user a DM instead.

@benfoxall do you think you could migrate (or just fork) the Code of Conduct to the DO org on github?

**Pull request closed without merging**
