### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by AverageMarcus**
Added some error handling and cleaned up some stuff thats not used.

### CODE REVIEW

**Review by danielthepope — CHANGES_REQUESTED** [review]
We killed Business Cat so we don't need it in `package.json`
But other than that it's fine. I thought about keeping example.coffee, but all our plugins are pure JS anyway...

**Comment by AverageMarcus** [comment]
We didn't kill business cat. We just limited what it responded to.

The example.coffee wasn't much use as it was out of date and used coffeescript. I think we have enough simple scripts that could be used as an example.

**Comment by danielthepope** [comment]
I refer you to https://github.com/jsoxford/hubot/commit/c138b3512cc9c815db5fbb0c7567c45b9c636ca8 ;)

**Comment by AverageMarcus** [comment]
😆  ok. I totally forgot about that.

**Review by danielthepope — APPROVED** [review]

**Pull request merged**
