### PR TITLE
Add "meet up" phrasing

### PR DESCRIPTION
**Pull request by omgmog**
To try and make this more @ninjanails proof!

### CODE REVIEW

**Comment by omgmog** [comment]
Also this would probably work by sticking a `\s?` in the `meetup` pattern, but uh...

**Comment by AverageMarcus** [comment]
You could just do `meet ?up` (I think)

**Comment by ninjanails** [comment]
Hehe but yay I made a change for the good happen ;P

**Comment by danielthepope** [comment]
Yeah, `meet\s?up` and `meet ?up` will both work. Personally I prefer the latter. At first glance the first one looks like it might match `meetsup`. That said, the way @omgmog has done it is really clear. So...
meh

**Pull request merged**
