### PR TITLE
kill business cat

### PR DESCRIPTION
**Pull request by omgmog**
Vote to kill the cat

:+1: kill it
:-1: let it live
:heart: bring the external plugin into our codebase and fiddle with the rules/triggers a bit.

### CODE REVIEW

**Comment by javorszky** [comment]
no! It's like spraying water on us when we're behaving naughty. Business cat serves a very important purpose! (now that I know what it's about)

**Comment by Drarok** [comment]
I vote we wait for some up/down votes via 👍 and 👎 and go with the majority!

**Comment by Drarok** [comment]
Maybe ❤️ to just adjust its trigger rules? 😁

**Comment by omgmog** [comment]
added description for the reactions to my initial PR message

**Comment by danielthepope** [comment]
We don't need to bring the code in, @AverageMarcus would just need to add the environment variable `HUBOT_BUSINESS_CAT_OMITTED_JARGON ='ooo'`
https://github.com/hubot-scripts/hubot-business-cat#configuration

**Comment by omgmog** [comment]
Even better then! The triggers list can be found here: https://github.com/hubot-scripts/hubot-business-cat/blob/master/src/data/triggers.json

**Comment by AverageMarcus** [comment]
Let me know what env var I need to add and I'll go add it

**Comment by AverageMarcus** [comment]
Ooo is no longer triggering business cat

**Comment by omgmog** [comment]
Can we also blacklist these:

```
alignment
at the end of the day
best practice
bleeding edge
bottom line
brain dump
brainstorm
brainstorming
going forward
in the loop
low hanging fruit
manifest
offsite
onboarding
(pie|bar|line|scatter) (chart|graph)
ping me
```

**Comment by AverageMarcus** [comment]
what does that leave us with?

**Comment by omgmog** [comment]
All the _truly_ wanky business cat phrases https://github.com/hubot-scripts/hubot-business-cat/blob/master/src/data/triggers.json

The ones I've selected there will probably be used genuinely on our Slack.

**Comment by AverageMarcus** [comment]
I'm gonna close this as it's been handled via env var now.

**Pull request closed without merging**
