### PR TITLE
Add Doxford

### LINKED ISSUE #28: Add doxford
> Someone remind me tomorrow to add doxford to hubot. :)

https://digitaloxford.slack.com/archives/general/p1460061730000962

### PR DESCRIPTION
**Pull request by AverageMarcus**
Fixed #28

### CODE REVIEW

**Comment by danielthepope** [comment]
Works for me! :+1:

**Comment by danielthepope** [comment]
Oh wait, I found a problem - you took out `created` from the API request in `new-meetup.js`, so it can't alert us when new Meetups get announced.

**Comment by AverageMarcus** [comment]
Doh! I'm away from keyboard right now. I'll sort it later.

**Comment by AverageMarcus** [comment]
@danielthepope Updated! :) Good spot!

**Comment by AverageMarcus** [comment]
Thinking about it, I may just use an API key in the future and add it a an env var in heroku. But I'll do that as a separate PR when I get round to it.

**Comment by danielthepope** [comment]
I quite like the idea of the presigned API requests, but it did take me a while to figure out how to sign them myself!
That said, I wouldn't be against that change. Just let me get my next change in beforehand :wink: (I've updated the URLs in meetup.js for a magic thing where Dobot is a little bit more conversational)

**Comment by AverageMarcus** [comment]
@benfoxall / @spikeheap / @peterjwest - Any of you happy to merge this?

**Comment by spikeheap** [comment]
:+1:

**Pull request merged**
