### PR TITLE
Add Oxford Hackspace to the ever-growing Meetup list

### PR DESCRIPTION
**Pull request by danielthepope**
"When's the next hackspace event?"

> The next Oxford Hackspace meetup is "_Open Night / Social Night_" on _Thursday 29th September at 7:00pm_. It's at _Oxford Hackspace_.
> http://www.meetup.com/Oxford-Hackspace/events/234324121/

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Is #hacks the right channel for this?

**Review by spikeheap — CHANGES_REQUESTED** [review]
Good call @AverageMarcus, this should probably be a new channel called #hackspace.

**Comment by AverageMarcus** [comment]
If you create a new channel you need to invite dobot to it before it can post there.

**Comment by danielthepope** [comment]
Removed the line where Dobot will post to #hacks. If you end up adding a channel for #hackspace, then sure, add it to the JSON. But since the channel isn't there, let's leave that for now.

**Review by AverageMarcus — APPROVED** [review]

**Pull request merged**
